[package]
name = "panel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-to-html = { version = "0.1.3", features = ["lazy-init"] }
async-std = "1.12.0"
axum = { version = "0.6.18", features = [
  "ws",
  "tokio",
  "http1",
  "matched-path",
] }
futures = "0.3.28"
minify-html = "0.11.1"
paste = "1.0.12"
tokio = { version = "1.28.2", features = [
  "macros",
  "net",
  "sync",
  "rt-multi-thread",
  "process",
] }
webhook = "2.1.2"
tokio-stream = "0.1.14"
futures-util = "0.3.28"
strip-ansi-escapes = "0.1.1"

[profile.release]
lto = true
strip = true
